/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.youssefbenavente.libreriadigital;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.Collection;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Youssef Benavente
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    DefaultListModel<String> listaLibros = new DefaultListModel<>();
    private ArrayList<Libro> libros = new ArrayList<>();
    String rutaGuardada;

    Libro libro1 = new Libro("Las 48 leyes del poder", "Robert Greene", "Libro de autoayuda", 1998, "El libro es una guía diseñada para mostrarle al lector cuáles son las cualidades personales que se deben tener para alcanzar el poder en términos sociológicos, un método práctico para todo aquel que quiera conseguir el poder, observar el poder o defenderse del poder.", "/images/Las48LeyesDelPoder.png");

    Libro libro2 = new Libro("Cien años de soledad", "Gabriel García Márquez", "Novela", 1967, "Una obra maestra de la literatura latinoamericana que narra la historia de la familia Buendía en el pueblo ficticio de Macondo, explorando temas de soledad, amor y destino.", "/images/CienAñosDeSoledad.jpg");

    Libro libro3 = new Libro("El arte de la guerra", "Sun Tzu", "Estratégia", -5000, "Un antiguo tratado chino sobre estrategia militar que ha influido en líderes militares y empresarios a lo largo de la historia.", "/images/ElArteDeLaGuerra.jpg");

    Libro libro4 = new Libro("1984", "George Orwell", "Distopía", 1949, "Una novela que presenta una sociedad totalitaria donde el gobierno controla todos los aspectos de la vida y la verdad es manipulada.", "/images/1984.jpg");

    Libro libro5 = new Libro("Orgullo y prejuicio", "Jane Austen", "Romance", 1813, "Una novela que explora las complicaciones del amor y las relaciones sociales en la Inglaterra del siglo XIX a través de la historia de Elizabeth Bennet y Mr. Darcy.", "/images/OrgulloYPrejuicio.jpg");

    Libro libro6 = new Libro("El Principito", "Antoine de Saint-Exupéry", "Fábula", 1943, "Una historia poética que narra las aventuras de un joven príncipe que viaja por diferentes planetas, reflexionando sobre la vida y las relaciones humanas.", "/images/ElPrincipito.jpg");

    Libro libro7 = new Libro("La sombra del viento", "Carlos Ruiz Zafón", "Novela", 2001, "Una novela que sigue la historia de un joven que descubre un libro en un misterioso cementerio de libros olvidados y se ve envuelto en un misterio literario que cambiará su vida.", "/images/LaSombraDelViento.jpg");

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        inicializarListaLibros();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaLibrosTenedor = new javax.swing.JList<>();
        jPanel6 = new javax.swing.JPanel();
        btnVerLibro = new javax.swing.JButton();
        btnEliminarLibro = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblFoto = new javax.swing.JLabel();
        lblAutorNoSeModifica = new javax.swing.JLabel();
        lblGeneroNoSeModifica = new javax.swing.JLabel();
        lblAñoNoSeModifica = new javax.swing.JLabel();
        lblSinopsisNoSeModifica = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaSinopsis = new javax.swing.JTextArea();
        lblEstadoNoSeModifica = new javax.swing.JLabel();
        cbEstadoLibro = new javax.swing.JComboBox<>();
        btnLibro = new javax.swing.JButton();
        lblVerAnio = new javax.swing.JLabel();
        lblVerGenero = new javax.swing.JLabel();
        lblVerAutor = new javax.swing.JLabel();
        btnGuardarEstado = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnOrgulloyPrejuicioAñadir = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnElPrincipitoAñadir = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnLaSombraDelVientoAñadir = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfIntroducirAutor = new javax.swing.JTextField();
        tfIntroducirGenero = new javax.swing.JTextField();
        tfIntroducirAño = new javax.swing.JTextField();
        tfIntroducirTitulo = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaSinopsisAñadir = new javax.swing.JTextArea();
        lblFotoAñadida = new javax.swing.JLabel();
        btnSeleccionarFoto = new javax.swing.JButton();
        btnGuardarLibro = new javax.swing.JButton();
        btnLimpiarFormulario = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LibreriaDigital by Youssef Benavente Chantoufi");
        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel4.setMaximumSize(new java.awt.Dimension(150, 100));
        jPanel4.setMinimumSize(new java.awt.Dimension(150, 100));
        jPanel4.setPreferredSize(new java.awt.Dimension(150, 100));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        listaLibrosTenedor.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Las 48 leyes del poder", "Cien años de soledad", "El arte de la guerra", "1984", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaLibrosTenedor.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaLibrosTenedor.setToolTipText("");
        jScrollPane1.setViewportView(listaLibrosTenedor);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.8;
        jPanel4.add(jScrollPane1, gridBagConstraints);

        btnVerLibro.setText("Ver Libro");
        btnVerLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerLibroActionPerformed(evt);
            }
        });
        jPanel6.add(btnVerLibro);

        btnEliminarLibro.setText("Eliminar ");
        btnEliminarLibro.setMinimumSize(new java.awt.Dimension(82, 27));
        btnEliminarLibro.setPreferredSize(null);
        btnEliminarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarLibroActionPerformed(evt);
            }
        });
        jPanel6.add(btnEliminarLibro);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        jPanel4.add(jPanel6, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jPanel4, gridBagConstraints);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("TITULO");
        lblTitulo.setToolTipText("");

        lblFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoto.setText("Sin Foto");
        lblFoto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblFoto.setMaximumSize(new java.awt.Dimension(200, 200));
        lblFoto.setMinimumSize(new java.awt.Dimension(200, 200));
        lblFoto.setPreferredSize(new java.awt.Dimension(200, 200));

        lblAutorNoSeModifica.setText("Autor:");

        lblGeneroNoSeModifica.setText("Genero:");

        lblAñoNoSeModifica.setText("Año:");

        lblSinopsisNoSeModifica.setText("Sinopsis:");

        txtAreaSinopsis.setEditable(false);
        txtAreaSinopsis.setColumns(20);
        txtAreaSinopsis.setRows(5);
        jScrollPane2.setViewportView(txtAreaSinopsis);

        lblEstadoNoSeModifica.setText("Estado");

        cbEstadoLibro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin leer", "En proceso", "Leído" }));

        btnLibro.setText("Abrir Libro");

        lblVerAnio.setText("jLabel1");

        lblVerGenero.setText("jLabel2");

        lblVerAutor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVerAutor.setText("jLabel3");

        btnGuardarEstado.setText("Guardar Cambios");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblAñoNoSeModifica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblAutorNoSeModifica, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblGeneroNoSeModifica, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(lblVerGenero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 287, Short.MAX_VALUE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblVerAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblVerAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSinopsisNoSeModifica)
                                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblEstadoNoSeModifica, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(cbEstadoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardarEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAutorNoSeModifica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblVerAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGeneroNoSeModifica)
                            .addComponent(lblVerGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAñoNoSeModifica)
                            .addComponent(lblVerAnio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSinopsisNoSeModifica)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblEstadoNoSeModifica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEstadoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarEstado))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.9;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jPanel5, gridBagConstraints);

        jTabbedPane1.addTab("Mis Libros", jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel7.setAutoscrolls(true);

        jPanel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel9.setMaximumSize(new java.awt.Dimension(528, 61));
        jPanel9.setMinimumSize(new java.awt.Dimension(528, 61));
        jPanel9.setLayout(new java.awt.BorderLayout(20, 20));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Orgullo y prejuicio");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 10, 2, 1));
        jPanel9.add(jLabel3, java.awt.BorderLayout.WEST);

        btnOrgulloyPrejuicioAñadir.setText("Añadir");
        btnOrgulloyPrejuicioAñadir.setMaximumSize(new java.awt.Dimension(76, 25));
        btnOrgulloyPrejuicioAñadir.setMinimumSize(new java.awt.Dimension(76, 25));
        btnOrgulloyPrejuicioAñadir.setPreferredSize(new java.awt.Dimension(76, 25));
        jPanel9.add(btnOrgulloyPrejuicioAñadir, java.awt.BorderLayout.EAST);

        jPanel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel13.setMaximumSize(new java.awt.Dimension(528, 61));
        jPanel13.setMinimumSize(new java.awt.Dimension(528, 61));
        jPanel13.setLayout(new java.awt.BorderLayout(20, 20));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("El Principito");
        jLabel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 10, 2, 1));
        jPanel13.add(jLabel7, java.awt.BorderLayout.WEST);

        btnElPrincipitoAñadir.setText("Añadir");
        btnElPrincipitoAñadir.setMaximumSize(new java.awt.Dimension(76, 25));
        btnElPrincipitoAñadir.setMinimumSize(new java.awt.Dimension(76, 25));
        btnElPrincipitoAñadir.setPreferredSize(new java.awt.Dimension(76, 25));
        jPanel13.add(btnElPrincipitoAñadir, java.awt.BorderLayout.EAST);

        jPanel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel14.setMaximumSize(new java.awt.Dimension(528, 61));
        jPanel14.setMinimumSize(new java.awt.Dimension(528, 61));
        jPanel14.setLayout(new java.awt.BorderLayout(20, 20));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("La sombra del viento");
        jLabel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 10, 2, 1));
        jPanel14.add(jLabel8, java.awt.BorderLayout.WEST);

        btnLaSombraDelVientoAñadir.setText("Añadir");
        btnLaSombraDelVientoAñadir.setMaximumSize(new java.awt.Dimension(76, 25));
        btnLaSombraDelVientoAñadir.setMinimumSize(new java.awt.Dimension(76, 25));
        btnLaSombraDelVientoAñadir.setPreferredSize(new java.awt.Dimension(76, 25));
        jPanel14.add(btnLaSombraDelVientoAñadir, java.awt.BorderLayout.EAST);

        jPanel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel15.setMaximumSize(new java.awt.Dimension(528, 61));
        jPanel15.setMinimumSize(new java.awt.Dimension(528, 61));
        jPanel15.setLayout(new java.awt.BorderLayout(20, 20));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Libro1");
        jLabel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 10, 2, 1));
        jPanel15.add(jLabel9, java.awt.BorderLayout.WEST);

        jButton11.setText("Añadir");
        jButton11.setMaximumSize(new java.awt.Dimension(76, 25));
        jButton11.setMinimumSize(new java.awt.Dimension(76, 25));
        jButton11.setPreferredSize(new java.awt.Dimension(76, 25));
        jPanel15.add(jButton11, java.awt.BorderLayout.EAST);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(315, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Biblioteca de Libros", jPanel7);

        jPanel8.setBackground(new java.awt.Color(32, 28, 28));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORMULARIO PARA AÑADIR LIBRO");

        tfIntroducirAutor.setBackground(new java.awt.Color(32, 28, 28));
        tfIntroducirAutor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Autor del Libro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        tfIntroducirAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIntroducirAutorActionPerformed(evt);
            }
        });

        tfIntroducirGenero.setBackground(new java.awt.Color(32, 28, 28));
        tfIntroducirGenero.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Genero del Libro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        tfIntroducirGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIntroducirGeneroActionPerformed(evt);
            }
        });

        tfIntroducirAño.setBackground(new java.awt.Color(32, 28, 28));
        tfIntroducirAño.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Año del Libro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        tfIntroducirAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIntroducirAñoActionPerformed(evt);
            }
        });

        tfIntroducirTitulo.setBackground(new java.awt.Color(32, 28, 28));
        tfIntroducirTitulo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Titulo del Libro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        tfIntroducirTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIntroducirTituloActionPerformed(evt);
            }
        });

        txtAreaSinopsisAñadir.setBackground(new java.awt.Color(32, 28, 28));
        txtAreaSinopsisAñadir.setColumns(20);
        txtAreaSinopsisAñadir.setLineWrap(true);
        txtAreaSinopsisAñadir.setRows(5);
        txtAreaSinopsisAñadir.setToolTipText("Escribe la sinopsis....");
        txtAreaSinopsisAñadir.setWrapStyleWord(true);
        txtAreaSinopsisAñadir.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sinopsis", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        jScrollPane3.setViewportView(txtAreaSinopsisAñadir);

        lblFotoAñadida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFotoAñadida.setText("Sin Foto");
        lblFotoAñadida.setToolTipText("");
        lblFotoAñadida.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblFotoAñadida.setMaximumSize(new java.awt.Dimension(200, 200));
        lblFotoAñadida.setMinimumSize(new java.awt.Dimension(200, 200));
        lblFotoAñadida.setPreferredSize(new java.awt.Dimension(200, 200));

        btnSeleccionarFoto.setText("Seleccionar Foto");
        btnSeleccionarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarFotoActionPerformed(evt);
            }
        });

        btnGuardarLibro.setText("Guardar");
        btnGuardarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarLibroActionPerformed(evt);
            }
        });

        btnLimpiarFormulario.setBackground(new java.awt.Color(255, 0, 0));
        btnLimpiarFormulario.setText("Limpiar Formulario");
        btnLimpiarFormulario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarFormularioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfIntroducirTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfIntroducirAño, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfIntroducirGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfIntroducirAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(btnGuardarLibro)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(0, 34, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFotoAñadida, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiarFormulario)
                    .addComponent(btnSeleccionarFoto)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(tfIntroducirTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfIntroducirAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfIntroducirGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfIntroducirAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFotoAñadida, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(btnSeleccionarFoto)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarLibro)
                    .addComponent(btnLimpiarFormulario))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Añadir Libro", jPanel8);

        jPanel2.add(jTabbedPane2);

        jTabbedPane1.addTab("Biblioteca", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Acerca de...", jPanel3);

        getContentPane().add(jTabbedPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfIntroducirAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIntroducirAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIntroducirAutorActionPerformed

    private void tfIntroducirGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIntroducirGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIntroducirGeneroActionPerformed

    private void tfIntroducirAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIntroducirAñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIntroducirAñoActionPerformed

    private void tfIntroducirTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIntroducirTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIntroducirTituloActionPerformed

    private void btnVerLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerLibroActionPerformed
        String nombre = listaLibrosTenedor.getSelectedValue(); // Título del libro seleccionado

        // Buscar el libro correspondiente
        for (Libro libro : libros) {
            if (libro.getTitulo().equals(nombre)) {
                // Mostrar los detalles del libro
                lblTitulo.setText(libro.getTitulo());
                lblVerAutor.setText(libro.getAutor());
                lblVerGenero.setText(libro.getGenero());
                lblVerAnio.setText(String.valueOf(libro.getAnio()));
                txtAreaSinopsis.setText(libro.getSinopsis());
                ImageIcon icon = new ImageIcon(getClass().getResource(libro.getUrlFoto()));
                lblFoto.setText("");
                lblFoto.setIcon(icon);

                return; // Salir del bucle una vez encontrado el libro
            }
        }

    }//GEN-LAST:event_btnVerLibroActionPerformed

    private void btnLimpiarFormularioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarFormularioActionPerformed
        //Boton que limpia el formulario dejandolo Vacio
        limpiarFormulario();

    }//GEN-LAST:event_btnLimpiarFormularioActionPerformed

    private void btnSeleccionarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarFotoActionPerformed
        // TODO add your handling code here:
        seleccionarFoto();
    }//GEN-LAST:event_btnSeleccionarFotoActionPerformed

    private void btnGuardarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarLibroActionPerformed
        // TODO add your handling code here:
        guardarLibro();
    }//GEN-LAST:event_btnGuardarLibroActionPerformed

    private void btnEliminarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarLibroActionPerformed
        // TODO add your handling code here:
        borrarLibro();
    }//GEN-LAST:event_btnEliminarLibroActionPerformed

    //Funciona
    private void limpiarFormulario() {
        tfIntroducirTitulo.setText("");
        tfIntroducirAutor.setText("");
        tfIntroducirAño.setText("");
        tfIntroducirGenero.setText("");
        txtAreaSinopsisAñadir.setText("");
        lblFotoAñadida.setText("Sin Foto");
        lblFotoAñadida.setIcon(null);
    }

    //comprobar
    private void borrarLibro() {
        int selectedIndex = listaLibrosTenedor.getSelectedIndex();
        if (selectedIndex != -1) {
            listaLibros.remove(selectedIndex);
            JOptionPane.showMessageDialog(this, "Libro eliminado exitosamente.");
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona un libro para eliminar.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    //comprobar
    private void inicializarListaLibros() {
        libros.add(libro1);
        libros.add(libro2);
        libros.add(libro3);
        libros.add(libro4);
        libros.add(libro5);
        libros.add(libro6);

        for (Libro libro : libros) {
            listaLibros.addElement(libro.getTitulo());
        }
        listaLibrosTenedor.setModel(listaLibros);
    }

    //Funciona
    private void seleccionarFoto() {
        // Crear un JFileChooser
        JFileChooser fileChooser = new JFileChooser();

        // Filtrar solo imágenes
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de imagen", "jpg", "png", "jpeg", "webp", "avif");
        fileChooser.setFileFilter(filtro);

        // Mostrar el JFileChooser y obtener la imagen seleccionada
        int resultado = fileChooser.showOpenDialog(this);

        // Si se seleccionó un archivo
        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivoSeleccionado = fileChooser.getSelectedFile();

            // Cargar la imagen en la etiqueta
            ImageIcon icon = new ImageIcon(archivoSeleccionado.getAbsolutePath());
            lblFotoAñadida.setIcon(icon);
            lblFotoAñadida.setText(""); // Limpiar texto si hay imagen

            // Define el directorio de destino (src/main/resources/images)
            String rutaDestino = "src/main/resources/images/" + archivoSeleccionado.getName();

            // Copiar la imagen seleccionada a la carpeta 'resources/images'
            File destino = new File(rutaDestino);
            copiarArchivo(archivoSeleccionado, destino);
                        rutaGuardada = archivoSeleccionado.getName();
        }
    }

    //Funciona
// Método para copiar el archivo a la carpeta destino
    private void copiarArchivo(File origen, File destino) {
        try (InputStream in = new FileInputStream(origen); OutputStream out = new FileOutputStream(destino)) {
            byte[] buffer = new byte[1024];
            int length;
            while ((length = in.read(buffer)) > 0) {
                out.write(buffer, 0, length);
                
            }
                        
            JOptionPane.showMessageDialog(this, "Imagen guardada exitosamente en: " + destino.getAbsolutePath());

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al guardar la imagen: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void guardarLibro() {
        // Obtener datos de los campos
        String titulo = tfIntroducirTitulo.getText().trim();
        String autor = tfIntroducirAutor.getText().trim();
        String genero = tfIntroducirGenero.getText().trim();
        String anioStr = tfIntroducirAño.getText().trim();
        String sinopsis = txtAreaSinopsisAñadir.getText().trim();
        String imagenUrl = "/images/"+rutaGuardada;

// Formatear la URL
        //String imagenUrl = nombreFoto; // Asumiendo que aquí se muestra el nombre del archivo

        // Validar que los campos no estén vacíos
        if (titulo.isEmpty() || autor.isEmpty() || genero.isEmpty() || anioStr.isEmpty() || sinopsis.isEmpty() || imagenUrl.equals("Sin Foto")) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Convertir año a entero
        int anio;
        try {
            anio = Integer.parseInt(anioStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El año debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Crear el objeto Libro
        Libro nuevoLibro = new Libro(titulo, autor, genero, anio, sinopsis, imagenUrl);

        // Añadir el libro a la lista
        listaLibros.addElement(nuevoLibro.getTitulo());
        libros.add(nuevoLibro);
        listaLibrosTenedor.setModel(listaLibros); // Asignar el DefaultListModel a la JList

        // Limpiar los campos después de añadir el libro
        limpiarFormulario();

        JOptionPane.showMessageDialog(this, "Libro guardado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        // añadir este codigo para adaptar la interfaz

        try {
            //codigo

            UIManager.setLookAndFeel(new FlatMacDarkLaf());

        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnElPrincipitoAñadir;
    private javax.swing.JButton btnEliminarLibro;
    private javax.swing.JButton btnGuardarEstado;
    private javax.swing.JButton btnGuardarLibro;
    private javax.swing.JButton btnLaSombraDelVientoAñadir;
    private javax.swing.JButton btnLibro;
    private javax.swing.JButton btnLimpiarFormulario;
    private javax.swing.JButton btnOrgulloyPrejuicioAñadir;
    private javax.swing.JButton btnSeleccionarFoto;
    private javax.swing.JButton btnVerLibro;
    private javax.swing.JComboBox<String> cbEstadoLibro;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lblAutorNoSeModifica;
    private javax.swing.JLabel lblAñoNoSeModifica;
    private javax.swing.JLabel lblEstadoNoSeModifica;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblFotoAñadida;
    private javax.swing.JLabel lblGeneroNoSeModifica;
    private javax.swing.JLabel lblSinopsisNoSeModifica;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVerAnio;
    private javax.swing.JLabel lblVerAutor;
    private javax.swing.JLabel lblVerGenero;
    private javax.swing.JList<String> listaLibrosTenedor;
    private javax.swing.JTextField tfIntroducirAutor;
    private javax.swing.JTextField tfIntroducirAño;
    private javax.swing.JTextField tfIntroducirGenero;
    private javax.swing.JTextField tfIntroducirTitulo;
    private javax.swing.JTextArea txtAreaSinopsis;
    private javax.swing.JTextArea txtAreaSinopsisAñadir;
    // End of variables declaration//GEN-END:variables
}
